/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.Controller.TreinoController;
import br.ulbra.dao.UsuarioDAO;
import br.ulbra.model.Treino;
import br.ulbra.model.Usuario;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class telaTreino extends javax.swing.JFrame {
    
    private Usuario usuarioLogado;        // usuário logado
    private TreinoController controller;  // controller de treinos
    private int treinoSelecionadoId = -1; // -1 = novo treino, outro valor = edição
    
// ===== CONSTRUTOR PADRÃO =====
    public telaTreino() throws SQLException {
        initComponents();

        // inicializa controller
        controller = new TreinoController();

        // registra listener uma vez aqui (fora do handler)
        tblTreino.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTreinoMouseClicked(evt);
            }
        });

        listarTreinos();
        setLocationRelativeTo(null); // centraliza a tela
    }

    // ===== EVENTO DE CLIQUE NA TABELA =====
    private void tblTreinoMouseClicked(java.awt.event.MouseEvent evt) {
        int linha = tblTreino.getSelectedRow();
        System.out.println("Clique detectado na linha: " + linha); // debug temporário — pode remover depois
        if (linha != -1) {
            try {
                // Ajuste os índices se a ordem das colunas for diferente
                treinoSelecionadoId = Integer.parseInt(tblTreino.getValueAt(linha, 0).toString());
                String tipo = tblTreino.getValueAt(linha, 1).toString();
                String duracao = tblTreino.getValueAt(linha, 2).toString();
                String calorias = tblTreino.getValueAt(linha, 3).toString();
                String dataTreino = tblTreino.getValueAt(linha, 4).toString();

                // Exibe nos campos
                txtTipoTreino.setText(tipo);
                txtDuracaoTreino.setText(duracao);
                txtCaloriasTreino.setText(calorias);
                txtDataTreino.setText(dataTreino);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao carregar dados da tabela: " + e.getMessage());
            }
        }
    }

    
    
    
    // ===== CONSTRUTOR COM USUÁRIO LOGADO =====
    public telaTreino(Usuario u) throws SQLException {
  initComponents();
        this.usuarioLogado = u;      // armazena o usuário logado

        // inicializa controller
        controller = new TreinoController();

        // registra listener uma vez aqui também
        tblTreino.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTreinoMouseClicked(evt);
            }
        });

        listarTreinos();
        setLocationRelativeTo(null); // centraliza a tela    
    }

    // ===== MÉTODO PARA LISTAR TODOS OS TREINOS =====
    private void listarTreinos() throws SQLException {
  List<Treino> lista;

        // se tiver usuário logado, lista só os treinos dele
        if (usuarioLogado != null) {
            lista = controller.listarPorUsuario(usuarioLogado.getId());
        } else {
            lista = controller.listar(); // lista todos
        }

        DefaultTableModel model = (DefaultTableModel) tblTreino.getModel();
        model.setRowCount(0); // limpa a tabela
        for (Treino t : lista) {
            model.addRow(new Object[]{
                t.getIdTreino(),
                t.getTipo(),
                t.getDuracao(),
                t.getCalorias(),
                t.getDataTreino()
            });
        }
 }

    // ===== MÉTODO PARA LIMPAR OS CAMPOS =====
    private void limparCampos() {
        txtTipoTreino.setText("");
        txtDuracaoTreino.setText("");
        txtCaloriasTreino.setText("");
        txtDataTreino.setText("");
        treinoSelecionadoId = -1; // reset
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTipoTreino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDuracaoTreino = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCaloriasTreino = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDataTreino = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTreino = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Duração(min):");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tipo:");

        txtDuracaoTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracaoTreinoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data de Treino:");

        txtCaloriasTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaloriasTreinoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Calorias:");

        txtDataTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataTreinoActionPerformed(evt);
            }
        });

        tblTreino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "COL_ID", "Tipo", "Duração (min)", "Calorias", "Data de Treino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTreino);

        btnSalvar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("ADICIONE OS SEUS DADOS DE TREINO:");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCaloriasTreino, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(txtDataTreino)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDuracaoTreino, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(txtTipoTreino))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTipoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDuracaoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCaloriasTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDataTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnVoltar)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CADASTRO DE TREINO");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\Documents\\NetBeansProjects\\FitTrack\\src\\br.ulbra.img\\LogoFitTrackBranco2.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCaloriasTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaloriasTreinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaloriasTreinoActionPerformed

    private void txtDataTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataTreinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataTreinoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
 try {
            if (usuarioLogado == null) {
                JOptionPane.showMessageDialog(this, "Nenhum usuário logado!");
                return;
            }

            // Validação de campos
            if (txtTipoTreino.getText().trim().isEmpty() ||
                txtDuracaoTreino.getText().trim().isEmpty() ||
                txtCaloriasTreino.getText().trim().isEmpty() ||
                txtDataTreino.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this, "Preencha todos os campos antes de salvar!");
                return;
            }

            Treino t = new Treino();
            t.setTipo(txtTipoTreino.getText());
            t.setDuracao(Integer.parseInt(txtDuracaoTreino.getText()));
            t.setCalorias(Double.parseDouble(txtCaloriasTreino.getText()));
            t.setDataTreino(txtDataTreino.getText());
            t.setIdUsuario(usuarioLogado.getId());

            if (treinoSelecionadoId != -1) {
                // Atualiza treino existente
                t.setIdTreino(treinoSelecionadoId);
                controller.atualizar(t);
                JOptionPane.showMessageDialog(null, "Treino atualizado com sucesso!");
                treinoSelecionadoId = -1;
            } else {
                // Novo treino
                controller.salvar(t);
                JOptionPane.showMessageDialog(null, "Treino salvo com sucesso!");
            }

            listarTreinos();
            limparCampos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Verifique se duração e calorias são números válidos!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar treino: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private static final int COL_TREINO_OBJ = 0; // ajuste conforme seu layout

    
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
int linha = tblTreino.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um treino para excluir!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Deseja realmente excluir este treino?",
            "Confirmar exclusão",
            JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            // fallback: tentar buscar pelo ID na linha
            Object idObj = tblTreino.getValueAt(linha, 0); // índice da coluna ID
            int id = Integer.parseInt(idObj.toString().trim());
            controller.removerPorId(id);
            JOptionPane.showMessageDialog(this, "Treino excluído com sucesso!");
            listarTreinos();
            limparCampos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir treino: " + ex.getMessage());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID inválido na linha selecionada.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new TelaInicial(usuarioLogado).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtDuracaoTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracaoTreinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracaoTreinoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
   if (treinoSelecionadoId == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um treino na tabela para editar!");
            return;
        }

        // Validação de campos obrigatórios
        if (txtTipoTreino.getText().trim().isEmpty() ||
            txtDuracaoTreino.getText().trim().isEmpty() ||
            txtCaloriasTreino.getText().trim().isEmpty() ||
            txtDataTreino.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Preencha todos os campos antes de salvar!");
            return;
        }

        try {
            Treino t = new Treino();
            t.setIdTreino(treinoSelecionadoId);
            t.setTipo(txtTipoTreino.getText());
            t.setDuracao(Integer.parseInt(txtDuracaoTreino.getText()));
            t.setCalorias(Double.parseDouble(txtCaloriasTreino.getText()));
            t.setDataTreino(txtDataTreino.getText());
            t.setIdUsuario(usuarioLogado.getId());

            controller.atualizar(t);

            JOptionPane.showMessageDialog(this, "Treino atualizado com sucesso!");
            listarTreinos();
            limparCampos();
            treinoSelecionadoId = -1;

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Verifique se duração e calorias são números válidos!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao editar treino: " + e.getMessage());
            }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new telaTreino().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(telaTreino.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTreino;
    private javax.swing.JTextField txtCaloriasTreino;
    private javax.swing.JTextField txtDataTreino;
    private javax.swing.JTextField txtDuracaoTreino;
    private javax.swing.JTextField txtTipoTreino;
    // End of variables declaration//GEN-END:variables
}
